### ISSUE TITLE
Detect available CPUs on Kubernetes

### ISSUE THREAD

**Issue by vever001** [theofidry/cpu-core-counter#125]
Coming from phpstan issue https://github.com/phpstan/phpstan/issues/7479

We are using a custom gitlab CI instance which uses kubernetes. It appears the detected CPU count there is the real amount of CPUs on the machine (36 in our case) while it is actually overridden and limited to 2 in gitlab CI via the KUBERNETES_CPU_LIMIT environment variable. Because of this phpstan was hanging intermittently (for some reason) so we had to resort to use phpstan `maximumNumberOfProcesses: 2`.

Is there a reliable way to detect the CPU limit, on kubernetes or any other docker container?
I don't have access to the actual machine and I have no idea how kubernetes works TBH.
Any thoughts?

Thank you

**Comment by Wirone** [comment]
Side note: PHPStan spawns main process + N child processes, so if you want to effectively parellelise the analysis, you need to have at least 3 CPUs (1 main + 2 workers). Same goes for [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7777) (funny, we also have [recent issue around CPU auto-detection](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8129), could it be related?).

**Comment by vever001** [comment]
Linking https://github.com/phpstan/phpstan/issues/7479#issuecomment-2761415907
Maybe the appropriate env var to check was KUBERNETES_CPU_REQUEST ?
I don't know much about gitlab/kubernetes and have no control/view on it as mere developer.
