### ISSUE TITLE
Fails on Windows 10

### ISSUE THREAD

**Issue by czukowski** [theofidry/cpu-core-counter#87]
I traced it down to this line where `filter_var` returns `false`:

https://github.com/theofidry/cpu-core-counter/blob/3a4682016af125f1f41d125798544641d49b79ae/src/Finder/ProcOpenBasedFinder.php#L91

The content of the `$process` variable was:

```
NumberOfLogicalProcessors  
8                          

```

This was my testing script:

```
use Fidry\CpuCoreCounter\CpuCoreCounter;

echo (new CpuCoreCounter())->getCount();
```

**Comment by theofidry** [comment]
Hi thanks for the report! You could tell me on which version this happened? I would expect it to have been fixed with https://github.com/theofidry/cpu-core-counter/pull/83 in 4.0.0

**Comment by czukowski** [comment]
Hi, it was version 0.4.0 according to composer.lock.

Basically I found out about this PR to PHPStan https://github.com/phpstan/phpstan-src/pull/2047 and I used the same version to test after noticing it's become much slower for me after a recent update as it was defaulting to running only one subprocess.

Please let me know if I can do anything else to help.

**Comment by theofidry** [comment]
I see, then I don't think it will be too hard to fix. I may be able to take a look at it next week or if you're keen you can also check #83 which should give enough examples on what to touch to fix & test it.
